name: docker-app
version: '0.1' 
summary: a dockerized app snap.
description: |
   a dockerized app snap that demostrates how to use docker or docker compose command 
   shared by docker snap.

grade: stable
confinement: strict

plugs:
  support:
    interface: docker-support
  privileged:
    interface: docker-support
    privileged-containers: true
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: docker-env

apps:
   ubuntu:
     command: docker-wrapper docker-compose -f $SNAP/services/ubuntu/docker-compose.yml up -d
     plugs: [network, docker-executables, docker-cli]
   redis-hello-world:
     command: docker-wrapper docker-compose -f $SNAP/services/redis-hello-world/docker-compose.yml up
     plugs: [network, docker-executables, docker-cli]

parts:
  environment:
    plugin: dump
    source: src/
    install: |
        mkdir $SNAPCRAFT_PART_INSTALL/docker-env
    organize:
      'docker-wrapper' : bin/
